models : 
  - name : customer_purchases
    columns :
     - name : key
       tests : 
        - unique
        - not_null

sources : 
  - name : tpch_sf1
    database : SNOWFLAKE_SAMPLE_DATA
    schema : TPCH_SF1
    tables : 
      - name : CUSTOMER
      - name : ORDERS